pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
}

rootProject.name = 'WorldGate'
include 'v26_1_2'
include 'v1_21_1'
include 'v1_20_1'
include 'v1_20_2'
include 'v1_20_3'
include 'v1_20_4'
include 'v1_20_5'
include 'v1_20_6'
include 'v1_20'
include 'v1_21'
include 'v1_21_2'
include 'v1_21_3'
include 'v1_21_4'
include 'v1_21_5'
include 'v1_21_6'
include 'v1_21_7'
include 'v1_21_8'
include 'v1_21_9'
include 'v1_21_10'
include 'v1_21_11'
include 'v26_2'
include 'v26_3'
