plugins {
    id 'fabric-loom' version "${loom_version}"
}

version = rootProject.mod_version
group = rootProject.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation "io.github.llamalad7:mixinextras-fabric:${mixinextras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-fabric:${mixinextras_version}"
    include "io.github.llamalad7:mixinextras-fabric:${mixinextras_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
