package com.rcraja.worldgate.network;
import com.rcraja.worldgate.Constants;
import com.rcraja.worldgate.WorldGateMod;
import java.io.InputStream;import java.net.URI;import java.net.http.*;import java.nio.file.*;import java.security.MessageDigest;import java.util.*;
public final class DynamicAssetManager{
 private static final long CACHE_LIMIT=256L*1024L*1024L;private static final Path ROOT=Paths.get(System.getProperty("user.home"),".worldgate","assets");private static final HttpClient HTTP=HttpClient.newBuilder().connectTimeout(java.time.Duration.ofSeconds(8)).build();
 private DynamicAssetManager(){}
 public static void refresh(){try{Files.createDirectories(ROOT);HttpRequest r=HttpRequest.newBuilder(URI.create(Constants.BACKEND_BASE_URL+"/v1/assets/manifest")).timeout(java.time.Duration.ofSeconds(10)).GET().build();HttpResponse<String> x=HTTP.send(r,HttpResponse.BodyHandlers.ofString());if(x.statusCode()>=200&&x.statusCode()<300)Files.writeString(ROOT.resolve("manifest.json"),x.body());cleanup();}catch(Exception e){WorldGateMod.LOGGER.debug("WorldGate asset manifest refresh failed",e);}}
 public static Path download(String id,String url,String expectedSha256){try{if(!expectedSha256.matches("[a-fA-F0-9]{64}"))return null;Files.createDirectories(ROOT);Path target=ROOT.resolve(safe(id));if(Files.exists(target)&&expectedSha256.equalsIgnoreCase(hash(target)))return target;Path tmp=ROOT.resolve(safe(id)+".part");long existing=Files.exists(tmp)?Files.size(tmp):0;HttpRequest.Builder rb=HttpRequest.newBuilder(URI.create(url)).timeout(java.time.Duration.ofSeconds(30)).GET();if(existing>0)rb.header("Range","bytes="+existing+"-");HttpResponse<InputStream>x=HTTP.send(rb.build(),HttpResponse.BodyHandlers.ofInputStream());if(x.statusCode()<200||x.statusCode()>=300)return null;boolean append=existing>0&&x.statusCode()==206;if(!append){existing=0;Files.deleteIfExists(tmp);}try(InputStream in=x.body();var out=Files.newOutputStream(tmp,append?new java.nio.file.OpenOption[]{StandardOpenOption.CREATE,StandardOpenOption.APPEND}:new java.nio.file.OpenOption[]{StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING})){in.transferTo(out);}if(!expectedSha256.equalsIgnoreCase(hash(tmp))){Files.deleteIfExists(tmp);return null;}Files.move(tmp,target,StandardCopyOption.REPLACE_EXISTING);cleanup();return target;}catch(Exception e){return null;}}
 private static String safe(String s){return s.replaceAll("[^a-zA-Z0-9._-]","_");}
 private static String hash(Path p)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=Files.newInputStream(p)){byte[]b=new byte[8192];int n;while((n=in.read(b))>0)d.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte b:d.digest())s.append(String.format("%02x",b));return s.toString();}
 private static void cleanup()throws Exception{if(!Files.exists(ROOT))return;List<Path>fs;try(var s=Files.list(ROOT)){fs=s.filter(Files::isRegularFile).filter(p->!p.getFileName().toString().equals("manifest.json")).toList();}long total=0;for(Path p:fs)total+=Files.size(p);if(total<=CACHE_LIMIT)return;ArrayList<Path>a=new ArrayList<>(fs);a.sort(Comparator.comparingLong(p->{try{return Files.getLastModifiedTime(p).toMillis();}catch(Exception e){return 0;}}));for(Path p:a){if(total<=CACHE_LIMIT)break;long n=Files.size(p);Files.deleteIfExists(p);total-=n;}}
}